### ISSUE TITLE
Basic TOML config

### ISSUE THREAD

**Issue by FBDev64** [Volt-Soft/Stellar-Engine#14]
Add TOML configuration for engine : 
```toml
[window]
width = 800
height = 600
fullscreen = false
title = "Stellar Game"
```
